<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="RequestIdType">
        <xs:restriction base="xs:string">
            <xs:minLength value="8"/>
            <xs:maxLength value="64"/>
            <xs:pattern value="[A-Za-z0-9_-]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TimestampType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="PatientIdType">
        <xs:restriction base="xs:string">
            <xs:pattern value="PA[0-9]{3,8}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="patientRecordRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="requestID" type="RequestIdType"/>
                <xs:element name="timeStamp" type="TimestampType"/>
                <xs:element name="patientID" type="PatientIdType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
